services:
  qgcontrol:
    build:
      context: .
      dockerfile: qgcontrol/qgcontrol_docker
    image: zawardo/qgcontrol:latest
    container_name: qgcontrol
    network_mode: host
    restart: no
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket
    devices:
      - /dev/dri:/dev/dri  # Enable GPU rendering (optional)


  micro_ros_agent:
    image: microros/micro-ros-agent:humble
    container_name: micro_ros_agent
    network_mode: host
    restart: no
    command: udp4 -p 2019 # Specify the arguments for the container
    stdin_open: true  # Keep stdin open for interactive mode
    tty: true

  ardupilot_ros_env:
    build:
      context: .
      dockerfile: ardupilot_ros/ardupilot_ros_docker
    image: zawardo/ardupilot_ros:latest
    container_name: ardupilot_ros
    network_mode: host
    restart: no
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket
      - /home/arthuino/stymphale_project/antikythera:/home/ardupilotuser/ros2_ws/src/antikythera  # Mount antikythera
    devices:
      - /dev/dri:/dev/dri  # Enable GPU rendering (optional)

  #dev_docker:

  
    