services:
  qgcontrol:
    build:
      context: .
      dockerfile: qgcontrol/qgcontrol_docker
    image: zawardo/qgcontrol:latest
    container_name: qgcontrol
    network_mode: host
    restart: "no"
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket
    devices:
      - /dev/dri:/dev/dri  # Enable GPU rendering (optional)


  micro_ros_agent:
    image: microros/micro-ros-agent:humble
    container_name: micro_ros_agent
    network_mode: host
    restart: "no"
    command: udp4 -p 2019 # Specify the arguments for the container
    stdin_open: true  # Keep stdin open for interactive mode
    tty: true

  ardupilot_ros_env:
    build:
      context: .
      dockerfile: ardupilot_ros/ardupilot_ros_docker
    image: zawardo/ardupilot_ros:latest
    container_name: ardupilot_ros
    network_mode: host
    restart: "no"
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket
      - /home/arthuino/stymphale_project/stymphale_ws:/home/ardupilotuser/stymphale_ws:rw  # Mount stymphale_ws
    devices:
      - /dev/dri:/dev/dri  # Enable GPU rendering

  cpp_ros_builder:
    build:
      context: .
      dockerfile: cpp_ros_builder/cpp_ros_builder_docker
      args:
        - MOUNT_DIR=/home/arthuino/stymphale_project/stymphale_ws
    image: arthuino/stymphale-cpp_ros_builder:latest
    container_name: cpp_ros_builder
    network_mode: host
    restart: "no"
    volumes:
      - type: bind
        source: /home/arthuino/stymphale_project/stymphale_ws
        target: /home/ardupilotuser/stymphale_ws/  # Mount stymphale_ws for building
    command: bash -c "rm -rf bash/ install/ log/ && colcon build --symlink-install --cmake-clean-cache --cmake-args -DCMAKE_VERBOSE_MAKEFILE=ON"

  cpp_ros_tester:
    build:
      context: .
      dockerfile: cpp_ros_builder/cpp_ros_builder_docker
      args:
        - ~/stymphale_project/stymphale_ws
    image: arthuino/stymphale-cpp_ros_builder:latest
    container_name: cpp_ros_tester
    network_mode: host
    restart: "no"
    volumes:
      - type: bind
        source: ~/stymphale_project/stymphale_ws
        target: /home/ardupilotuser/stymphale_ws/  # Mount stymphale_ws for building
    command: colcon test --ctest-args tests

  cpp_ros_test_results:
    build:
      context: .
      dockerfile: cpp_ros_builder/cpp_ros_builder_docker
      args:
        - ~/stymphale_project/stymphale_ws
    image: arthuino/stymphale-cpp_ros_builder:latest
    container_name: cpp_ros_test_results
    network_mode: host
    restart: "no"
    volumes:
      - type: bind
        source: ~/stymphale_project/stymphale_ws
        target: /home/ardupilotuser/stymphale_ws/  # Mount stymphale_ws for building
    command: colcon test-result --all --verbose

    