name: Antikythera Cpp Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # print the current directory
      - name: Print current directory
        run: pwd && ls -a

      - name: Run Tester docker
        uses: hoverkraft-tech/compose-action@main
        with:
          compose-file: zawardo_drone/.config/compose.yaml
          services: cpp_ros_autotester


