name: Antikythera Cpp Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # print the current directory
      - name: Print current directory
        run: pwd && ls -a

      - name: Run Tester docker
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: "compose.yaml"
          service: "cpp_ros_autotester"
          command: bash -c "colcon test --ctest-args tests && colcon test-result --all --verbose"
          registry: "arthuino"

          
