name: Antikythera Cpp Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # print the current directory
      - name: Print current directory
        run: pwd && ls -a

      - name: Run Tester docker
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: zawardo_drone/.config/compose.yaml
          service: cpp_ros_autotester


