name: Antikythera Cpp Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # print the current directory
      - name: Install compose
        run: sudo apt-get install docker-compose

      - name: Debuging
        run: docker-compose --version

      - name: pulling docker image
        run: docker pull arthuino/stymphale-cpp_ros_builder:latest

      - name: Create user
        run: sudo groupadd -g 1004 ardupilotgroup && sudo useradd -u 1003 -g 1004 -ms /bin/bash ardupilotuser

      - name: Build Workspace
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: zawardo_drone/.config/workflow-compose.yaml
          service: cpp_ros_autobuilder

      - name: Run Tester docker
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: zawardo_drone/.config/workflow-compose.yaml
          service: cpp_ros_autotester

        


